<?xml version="1.0"?>
<package format="3">
  <name>quad_bringup</name>
  <version>0.1.0</version>
  <description>
    Paquete de arranque (bringup) para el robot cuadrúpedo.
    Inicializa teleoperación, gait, cinemática inversa (IK), y micro-ROS.
  </description>

  <maintainer email="andres34f@gmail.com">Andrés Ruano</maintainer>
  <author email="andres34f@gmail.com">Andrés Ruano</author>

  <license>MIT</license>

  <!-- Dependencias de ROS2 necesarias -->
  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>launch</depend>
  <depend>launch_ros</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>std_msgs</depend>
  <depend>joy</depend>
  <depend>micro_ros_agent</depend>

  <!-- Dependencias opcionales para simulación -->
  <exec_depend>gazebo_ros</exec_depend>

  <!-- Exportar aament -->
  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
