<?xml version="1.0"?>
<package format="3">
  <name>quad_gait</name>
  <version>0.0.1</version>
  <description>
    Paquete para el robot cuadrúpedo, incluye gait planner y body motion planner.
  </description>

  <maintainer email="andres34f@gmail.com">Andrés Ruano</maintainer>
  <license>MIT</license>

  <!-- Dependencias necesarias para ROS2 Python -->
  <exec_depend>rclpy</exec_depend>
  <exec_depend>std_msgs</exec_depend>

  <!-- Dependencia de mensajes personalizados -->
  <exec_depend>quad_msgs</exec_depend>

  <build_depend>quad_msgs</build_depend>
  <build_export_depend>quad_msgs</build_export_depend>
  <exec_depend>quad_msgs</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>